# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb91e1289550127ea70667318391b30969fd467dc78802a57e657aeaaf5fe85eab09afcd4af2fd84070959c2eb8480a8c83983d1fee528c8b12895f5c41247eb

test:
  secret_key_base: c36810c72862056b97441ca5c566572e72d4ebec33bcd0f060e612d3c3050bbd708a0d7053780cccde25ae68edc5e0ef3c3cc3a000f04ef4853ba79ea25eda20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
